### ISSUE TITLE
[CRASH] Tried to handle a committed transaction in the pool but its nonce doesn't match the head of the queue for that sender.

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#4298]
This error becomes more prevalent while the faucet is running and sending a high volume of transactions from the same address. 

```
(monitor.ml.Error
  (Failure
    "Tried to handle a committed transaction in the pool but its nonce doesn't match the head of the queue for that sender.")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 257, characters 14-107"
    "Called from file \"list.ml\", line 117, characters 24-34"
    "Called from file \"src/list0.ml\" (inlined), line 22, characters 40-81"
    "Called from file \"src/lib/network_pool/transaction_pool.ml\", line 229, characters 8-1023"
    "Called from file \"src/lib/pipe_lib/broadcast_pipe.ml\", line 89, characters 25-28"
    "Called from file \"src/pipe.ml\", line 827, characters 4-56"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 171, characters 6-47"
    "Caught by monitor coda"))
```

**Comment by yourbuddyconner** [comment]
Original Ticket from December 12th: 
https://github.com/CodaProtocol/coda/issues/4066

Other Occurences: 
https://github.com/CodaProtocol/coda/issues/4287
https://github.com/CodaProtocol/coda/issues/4281
https://github.com/CodaProtocol/coda/issues/4272
https://github.com/CodaProtocol/coda/issues/4262
https://github.com/CodaProtocol/coda/issues/4260
https://github.com/CodaProtocol/coda/issues/4258

**Comment by imeckler** [comment]
@deepthiskumar has identified the root cause and should be fixed in her upcoming PR

**Comment by aneesharaines** [comment]
Tests are flakey and need to be addressed.

**Comment by yourbuddyconner** [comment]
Still seeing this bug in Develop, I believe @deepthiskumar is working on a PR we believe will remedy the situation.

**Comment by deepthiskumar** [comment]
@yourbuddyconner  Merged #4391 this morning. Did the build include this pr?

**Comment by yourbuddyconner** [comment]
It did indeed this is the PR for the branch I am working off of: https://github.com/CodaProtocol/coda/pulls

**Comment by imeckler** [comment]
@nholland94 and @imeckler to code-owner review https://github.com/CodaProtocol/coda/pull/4418/files

**Comment by yourbuddyconner** [comment]
I am running a Testnet that will run over the weekend, but so far there have been 45 blocks produced with no issues! 🎊
